# Generated by Django 4.1.4 on 2022-12-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="votes",
            new_name="votes_to_skip",
        ),
    ]
